# Generated by Django 3.1.2 on 2020-10-30 00:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workout.user')),
            ],
        ),
        migrations.CreateModel(
            name='personalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerciseName', models.CharField(max_length=250)),
                ('weightReps', models.CharField(max_length=10)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PR', to='workout.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersPRs', to='workout.user')),
            ],
        ),
        migrations.CreateModel(
            name='excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerciseName', models.CharField(max_length=250)),
                ('sets', models.IntegerField(blank=True)),
                ('reps', models.IntegerField(blank=True)),
                ('effort', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecises', to='workout.workout')),
            ],
        ),
    ]
