# Generated by Django 3.1.2 on 2020-11-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20201122_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='excercise',
            new_name='exercise',
        ),
    ]
