# Generated by Django 3.1.2 on 2020-12-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20201123_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='excerciseName',
            new_name='exerciseName',
        ),
        migrations.RenameField(
            model_name='personalrecord',
            old_name='excercise',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='personalrecord',
            old_name='excerciseName',
            new_name='exerciseName',
        ),
    ]
