# Generated by Django 3.1.2 on 2020-12-07 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20201202_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='effort',
        ),
        migrations.AddField(
            model_name='workout',
            name='effort',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
